return {
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Dismantling",
	},
	Description = T(980203993863, --[[ModItemActivityGroup Dismantle_JE Description]] "Dismantling old gear"),
	DisplayName = T(294678436895, --[[ModItemActivityGroup Dismantle_JE DisplayName]] "Dismantle"),
	DisplayNameShortened = T(813891129432, --[[ModItemActivityGroup Dismantle_JE DisplayNameShortened]] "Dismantle"),
	SortKey = 19,
	id = "Dismantle_JE",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"CarryAway",
		"Manipulation",
	},
	Description = T(796979033750, --[[ModItemActivityGroup JE_Manipulation Description]] 'Survivors will perform "manipulation" activities like loading smelters, fermenters, and etc.'),
	DisplayName = T(881961985433, --[[ModItemActivityGroup JE_Manipulation DisplayName]] "Manipulation"),
	DisplayNameShortened = T(870329957941, --[[ModItemActivityGroup JE_Manipulation DisplayNameShortened]] "Manip."),
	SortKey = 17,
	id = "JE_Manipulation",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Rescuing",
	},
	Description = T(988608674316, --[[ModItemActivityGroup Rescue Description]] "Survivors will rescue other survivors in need."),
	DisplayName = T(982290907203, --[[ModItemActivityGroup Rescue DisplayName]] "Rescue"),
	DisplayNameShortened = T(572867652932, --[[ModItemActivityGroup Rescue DisplayNameShortened]] "Rescue"),
	SortKey = 11,
	id = "Rescue",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"HealSelf",
	},
	Description = T(973812710338, --[[ModItemActivityGroup JE_HealSelf Description]] "Healing of oneself."),
	DisplayName = T(618454958843, --[[ModItemActivityGroup JE_HealSelf DisplayName]] "Heal Self"),
	DisplayNameShortened = T(879544134944, --[[ModItemActivityGroup JE_HealSelf DisplayNameShortened]] "Self Heal"),
	SortKey = 9,
	id = "JE_HealSelf",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Butchering",
	},
	Description = T(617940109841, --[[ModItemActivityGroup Butcher_JE Description]] "Butchering of hunted animals"),
	DisplayName = T(504095195951, --[[ModItemActivityGroup Butcher_JE DisplayName]] "Butchering"),
	DisplayNameShortened = T(717047143640, --[[ModItemActivityGroup Butcher_JE DisplayNameShortened]] "Butcher"),
	SortKey = 42,
	id = "Butcher_JE",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Slaughtering",
	},
	Description = T(999957043609, --[[ModItemActivityGroup Slaughter_JE Description]] "The Slaughter of Domesticate animals."),
	DisplayName = T(500733249343, --[[ModItemActivityGroup Slaughter_JE DisplayName]] "Slaughtering"),
	DisplayNameShortened = T(561375357946, --[[ModItemActivityGroup Slaughter_JE DisplayNameShortened]] "Slaughter"),
	SortKey = 43,
	id = "Slaughter_JE",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Salvaging",
	},
	Description = T(964438848092, --[[ModItemActivityGroup Salvage_JE Description]] "Scavenging for usable resources via Salvage."),
	DisplayName = T(376264661385, --[[ModItemActivityGroup Salvage_JE DisplayName]] "Salvage"),
	DisplayNameShortened = T(433715841190, --[[ModItemActivityGroup Salvage_JE DisplayNameShortened]] "Salvage"),
	SortKey = 76,
	id = "Salvage_JE",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Repair",
	},
	Description = T(674559194844, --[[ModItemActivityGroup Repair_JE Description]] "Repairing of damaged and malfunctioning structures and devices."),
	DisplayName = T(280549705161, --[[ModItemActivityGroup Repair_JE DisplayName]] "Repair"),
	DisplayNameShortened = T(720080960029, --[[ModItemActivityGroup Repair_JE DisplayNameShortened]] "Repair"),
	SortKey = 31,
	id = "Repair_JE",
}),
PlaceObj('ModItemActivityGroup', {
	Activities = {
		"Deconstruction",
	},
	Description = T(810154063074, --[[ModItemActivityGroup Deconstruct_JE Description]] "Deconstructing devices and structures."),
	DisplayName = T(133071819969, --[[ModItemActivityGroup Deconstruct_JE DisplayName]] "Deconstruct"),
	DisplayNameShortened = T(317276392378, --[[ModItemActivityGroup Deconstruct_JE DisplayNameShortened]] "Deconstruct"),
	SortKey = 32,
	id = "Deconstruct_JE",
}),
PlaceObj('ModItemActivitySet', {
	Activities = set( "Assembling", "AwaitTreatment", "BoardRescuePod", "BoardTradingPod", "CarryAway", "Celebrate", "Crafting", "DeliveryActivityObject", "Dismantling", "Equip", "FeedingSurvivor", "FollowLeader", "GetMoney", "HealAnimal", "HealSelf", "Healing", "MedicalBedTreatment", "PrepareForExpedition", "Rescuing", "Tailoring", "Unequip", "UnequipCorpse" ),
	BackgroundColor = 4291262730,
	Description = T(398274097917, --[[ModItemActivitySet Craft Description]] "Dedicated hours for Assembling, Crafting and Tailoring tasks."),
	DisplayName = T(683051489335, --[[ModItemActivitySet Craft DisplayName]] "Craft"),
	DisplayNameUpper = T(715557350589, --[[ModItemActivitySet Craft DisplayNameUpper]] "CRAFT"),
	SortKey = 14,
	TextColor = 4294040001,
	TextShadowColor = 3257016349,
	id = "Craft",
}),
PlaceObj('ModItemActivitySet', {
	Activities = {
		AwaitTreatment = true,
		BoardRescuePod = true,
		BoardTradingPod = true,
		CarryAway = true,
		Celebrate = true,
		Chopping = true,
		Cooking = true,
		Cutting = true,
		Delivery = true,
		DeliveryActivityObject = true,
		Equip = true,
		FeedingAnimal = true,
		FeedingSurvivor = true,
		Fertilizing = true,
		FollowLeader = true,
		GetMoney = true,
		Harvesting = true,
		HealAnimal = true,
		HealSelf = true,
		Healing = true,
		LeadAnimal = true,
		MedicalBedTreatment = true,
		Planting = true,
		PrepareForExpedition = true,
		Ranching = true,
		Rescuing = true,
		Slaughtering = true,
		TrainAnimal = true,
		Unequip = true,
		UnequipCorpse = true,
	},
	BackgroundColor = 4280985172,
	Description = T(660466496707, --[[ModItemActivitySet Farm_Cook Description]] "Dedicated hours for all Cooking, Ranching and Farming related activities (including Cutting and Chopping)"),
	DisplayName = T(843321261004, --[[ModItemActivitySet Farm_Cook DisplayName]] "Farm"),
	DisplayNameUpper = T(820304698179, --[[ModItemActivitySet Farm_Cook DisplayNameUpper]] "FARM"),
	SortKey = 17,
	TextColor = 4292209344,
	TextShadowColor = 3239187220,
	id = "Farm_Cook",
}),
PlaceObj('ModItemActivitySet', {
	Activities = set( "AwaitTreatment", "BoardRescuePod", "BoardTradingPod", "Celebrate", "DeliveryActivityObject", "Equip", "FeedingSurvivor", "FollowLeader", "GetMoney", "HealAnimal", "HealSelf", "Healing", "MedicalBedTreatment", "Mining", "PrepareForExpedition", "Rescuing", "Salvaging", "Scavenging", "Unequip", "UnequipCorpse" ),
	BackgroundColor = 4285229416,
	Description = T(313883946445, --[[ModItemActivitySet Scavenge Description]] "Dedicated hours for Salvaging, Scavenging AND mining activities."),
	DisplayName = T(360520963381, --[[ModItemActivitySet Scavenge DisplayName]] "Scavenge"),
	DisplayNameUpper = T(136232736673, --[[ModItemActivitySet Scavenge DisplayNameUpper]] "SCAVENGE"),
	SortKey = 13,
	TextColor = 4293583581,
	TextShadowColor = 3256029713,
	id = "Scavenge",
}),
PlaceObj('ModItemActivitySet', {
	Activities = {
		AwaitTreatment = true,
		BoardRescuePod = true,
		BoardTradingPod = true,
		Burying = true,
		Butchering = true,
		CarryAway = true,
		Celebrate = true,
		Combat = true,
		Delivery = true,
		DeliveryActivityObject = true,
		Dismantling = true,
		Equip = true,
		ExpeditionRewardsDelivery = true,
		FeedingAnimal = true,
		FeedingSurvivor = true,
		FollowLeader = true,
		GetMoney = true,
		HealAnimal = true,
		HealSelf = true,
		Healing = true,
		LeadAnimal = true,
		LoadPod = true,
		Manipulation = true,
		MedicalBedTreatment = true,
		PrepareForExpedition = true,
		Rescuing = true,
		Slaughtering = true,
		TrainAnimal = true,
		Unequip = true,
		UnequipCorpse = true,
		UnloadPod = true,
	},
	BackgroundColor = 4292855121,
	Description = T(429374071789, --[[ModItemActivitySet Deliver Description]] "Dedicated hours for performing just delivery and handle tasks.  Survivors will also butcher and slaughter during this time, if those tasks come up.  Sleeping and Eating is forbidden."),
	DisplayName = T(533416725727, --[[ModItemActivitySet Deliver DisplayName]] "Deliver"),
	DisplayNameUpper = T(537601783672, --[[ModItemActivitySet Deliver DisplayNameUpper]] "DELIVER"),
	SortKey = 25,
	TextColor = 4294307560,
	TextShadowColor = 3190104355,
	id = "Deliver",
}),
PlaceObj('ModItemActivitySet', {
	Activities = set( "AwaitTreatment", "BoardRescuePod", "BoardTradingPod", "Celebrate", "Equip", "FeedingSurvivor", "FieldResearch", "FollowLeader", "GetMoney", "HealAnimal", "HealSelf", "Healing", "MedicalBedTreatment", "PrepareForExpedition", "Rescuing", "Research", "Unequip", "UnequipCorpse" ),
	BackgroundColor = 4287590641,
	Description = T(499116107980, --[[ModItemActivitySet FieldResearch Description]] "Dedicated hours for field research (observing) and researching new technologies."),
	DisplayName = T(408625201445, --[[ModItemActivitySet FieldResearch DisplayName]] "Observation and Research"),
	DisplayNameUpper = T(869002230161, --[[ModItemActivitySet FieldResearch DisplayNameUpper]] "SCIENCE"),
	SortKey = 15,
	TextColor = 4292597234,
	TextShadowColor = 3290570792,
	id = "FieldResearch",
}),
PlaceObj('ModItemActivitySet', {
	Activities = {
		AwaitTreatment = true,
		BoardRescuePod = true,
		BoardTradingPod = true,
		Burying = true,
		Celebrate = true,
		Construction = true,
		Deconstruction = true,
		DeliveryActivityObject = true,
		Equip = true,
		FeedingSurvivor = true,
		FollowLeader = true,
		GetMoney = true,
		HealSelf = true,
		Healing = true,
		PrepareForExpedition = true,
		Repair = true,
		Rescuing = true,
		Unequip = true,
		UnequipCorpse = true,
		Upgrade = true,
	},
	BackgroundColor = 4283670961,
	Description = T(307280691225, --[[ModItemActivitySet Build Description]] "Dedicated hours for construction and repair tasks."),
	DisplayName = T(177597978070, --[[ModItemActivitySet Build DisplayName]] "Build"),
	DisplayNameUpper = T(861148483827, --[[ModItemActivitySet Build DisplayNameUpper]] "BUILD"),
	SortKey = 4,
	TextColor = 4293977562,
	TextShadowColor = 4278190080,
	id = "Build",
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Work",
	'TargetProp', "Activities",
	'TargetValue', set( "Assembling", "AwaitTreatment", "BoardRescuePod", "BoardTradingPod", "Burying", "Butchering", "CarryAway", "Celebrate", "Chopping", "Combat", "Construction", "Cooking", "Crafting", "Cutting", "Deconstruction", "Delivery", "DeliveryActivityObject", "Dismantling", "Equip", "ExpeditionRewardsDelivery", "FeedingAnimal", "FeedingSurvivor", "Fertilizing", "FieldResearch", "Fishing", "FollowLeader", "GetMoney", "Harvesting", "HealAnimal", "HealSelf", "Healing", "Hunting", "LeadAnimal", "LoadPod", "Manipulation", "MedicalBedTreatment", "Mining", "PacifyUnit", "Planting", "PrepareForExpedition", "Ranching", "Repair", "Rescuing", "Research", "Salvaging", "Scavenging", "Slaughtering", "Tailoring", "TrainAnimal", "Unequip", "UnequipCorpse", "UnloadPod", "Upgrade" ),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Work",
	'TargetProp', "Description",
	'TargetValue', T(225516247641, "Dedicated hours for working HARD. Eating, Relaxing and sleeping are forbidden."),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Work",
	'TargetProp', "BackgroundColor",
	'TargetValue', RGBA(232, 5, 53, 255),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Work",
	'TargetProp', "TextColor",
	'TargetValue', RGBA(238, 228, 222, 255),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Work",
	'TargetProp', "TextShadowColor",
	'TargetValue', RGBA(82, 44, 67, 190),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Sleep",
	'TargetProp', "TextColor",
	'TargetValue', RGBA(211, 221, 246, 255),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Sleep",
	'TargetProp', "TextShadowColor",
	'TargetValue', RGBA(32, 38, 52, 255),
}),
PlaceObj('ModItemChangeProp', {
	'TargetClass', "ActivitySet",
	'TargetId', "Sleep",
	'TargetProp', "Activities",
	'TargetValue', set( "AwaitTreatment", "BoardRescuePod", "BoardTradingPod", "Celebrate", "FeedingSurvivor", "HealAnimal", "HealSelf", "Healing", "MedicalBedTreatment", "Relaxing", "Rescuing", "Sleeping" ),
}),
PlaceObj('ModItemChangeProp', {
	'name', "Construction_Activities",
	'TargetClass', "ActivityGroup",
	'TargetId', "Construct",
	'TargetProp', "Activities",
	'TargetValue', {
		"Construction",
		"Upgrade",
	},
}),
PlaceObj('ModItemChangeProp', {
	'name', "Handle_Activities",
	'TargetClass', "ActivityGroup",
	'TargetId', "Handle",
	'TargetProp', "Activities",
	'TargetValue', {
		"Burying",
		"LoadPod",
		"UnloadPod",
		"UnequipCorpse",
	},
}),
PlaceObj('ModItemChangeProp', {
	'name', "Handle_Description",
	'TargetClass', "ActivityGroup",
	'TargetId', "Handle",
	'TargetProp', "Description",
	'TargetValue', T(480528739379, "Handles the loading and unloading of pods as well as burying the dead."),
}),
PlaceObj('ModItemChangeProp', {
	'name', "Handle_Shortname",
	'TargetClass', "ActivityGroup",
	'TargetId', "Handle",
	'TargetProp', "DisplayNameShortened",
	'TargetValue', T(108665916543, "Load"),
}),
PlaceObj('ModItemChangeProp', {
	'name', "Handle_name",
	'TargetClass', "ActivityGroup",
	'TargetId', "Handle",
	'TargetProp', "DisplayName",
	'TargetValue', T(888516121649, "Load Pod"),
}),
PlaceObj('ModItemChangeProp', {
	'name', "Heal_Activities",
	'TargetClass', "ActivityGroup",
	'TargetId', "Heal",
	'TargetProp', "Activities",
	'TargetValue', {
		"Healing",
		"HealAnimal",
	},
}),
PlaceObj('ModItemChangeProp', {
	'name', "Heal_Name",
	'TargetClass', "ActivityGroup",
	'TargetId', "Heal",
	'TargetProp', "DisplayName",
	'TargetValue', T(628217709530, "Heal Others"),
}),
PlaceObj('ModItemChangeProp', {
	'name', "Heal_Shortname",
	'TargetClass', "ActivityGroup",
	'TargetId', "Heal",
	'TargetProp', "DisplayNameShortened",
	'TargetValue', T(482355504993, "Heal Others"),
}),
PlaceObj('ModItemChangeProp', {
	'name', "Hunt_Activities",
	'TargetClass', "ActivityGroup",
	'TargetId', "Hunt",
	'TargetProp', "Activities",
	'TargetValue', {
		"Hunting",
	},
}),
PlaceObj('ModItemChangeProp', {
	'name', "Scavenge_Activities",
	'TargetClass', "ActivityGroup",
	'TargetId', "Scavenge",
	'TargetProp', "Activities",
	'TargetValue', {
		"Scavenging",
	},
}),
}
