return PlaceObj('ModDef', {
	'title', "Jaggid's Taskmaster - Redux",
	'description', 'Maintained fork of Jaggid Edje\'s [url=https://steamcommunity.com/sharedfiles/filedetails/?id=2972040553][b]Jaggid\'s Taskmaster[/b][/url], published with the original author\'s permission. All activity-group splits and schedule designs are Jaggid\'s; this fork only fixes small bugs in the descriptions. See the changelog or [url=https://github.com/Sisyphus192/Jaggid-s-Taskmaster-Redux]GitHub repo[/url] for details.\n\nAdded new work assignments for the Schedule planner so that work could be better scheduled and broke out several tasks into independent Activity groups for prioritization on the Acvitivy planner.\n\n[hr][/hr]\n[h1][b]Activity Planner[/b][/h1]\n[list][*]Split out Healing and Healing of Self so that you can prioritize them differently. \n[*]Split out the Handle task so that Rescue, Dismantle, Load and Manipulation can be seperately prioritized.  Note that "manipulation" covers the handling of devices, such as smelters, fermenters, making tea, etc. and "Load" is the loading and unloading of Trading Pods (as well as looting of corpses and burying the dead).\n[*]Split out the Hunting task so that Hunting, Butchering, and Slaughtering can each be prioritized seperately.  \n[*]Split out the Scavenging task so that Scavenge and Salvage can be prioritized seperately.\n[*]Split out the Construction activity so that Construction, Repairs, and Deconstruction can be prioritized seperately.\n[/list]\n\n[hr][/hr]\n[h1][b]Schedule Assignments[/b][/h1]\n[list][*][b]Farm[/b] (& Cook) - Cooking meals, as well as all farming/ranching related activities (including Cutting and Chopping) with no breaks to eat, relax or sleep.\n[*][b]Craft[/b] - All crafting tasks (including Tailoring and Soldering, etc., with no breaks for meals.\n[*][b]Work[/b] - Edited the game\'s default work assignment to remove \'eating\'.  For those times when you want your survivors NOT to stop for meal breaks.\n[*][b]Scavenge[/b] - Mining, scavenging and Salvaging.  No cutting or chopping.  With no breaks for meals.\n[*][b]Science[/b] - Research and Observation, with no breaks for meals.\n[*][b]Build[/b] - Construction related activities, including upgrades, repairs and deconstruction, with no Breaks for meals.\n[*][b]Sleep[/b] - Modified version of the game\'s standard Sleep assignment.  Forbids eating, so your survivors will not eat even if hungry until they wake up.  \n[/list]\nBe advised that all of the above new work schedule assignments have eating excluded.  So make sure to leave some time with other assignments in the schedule or your survivors might die. \n\nThe game\'s default work schedule groups of Anything and Relax also remain and do allow eating.\n\nDo not use with other mods that also adjust activity sets to avoid conflicts.',
	'image', "Mod/jaggids_taskmaster_redux/Images/Taskmaster_Preview.png",
	'last_changes', '1.10-169 (first Redux release)\n- Clarified Craft activity-set tooltip to mention Cooking is included (matches actual behavior)\n- Fixed Scavenge activity-set tooltip typo ("Scrapping" -> "Scavenging") and stray double period',
	'id', "jaggids_taskmaster_redux",
	'author', "Jaggid Edje (Redux maintained by Sisyphus192)",
	'version_major', 1,
	'version_minor', 10,
	'version', 169,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'has_data', true,
	'saved', 1777762087,
	'screenshot1', "Mod/jaggids_taskmaster_redux/Images/Taskmaster_Screenshot1.jpg",
	'screenshot2', "Mod/jaggids_taskmaster_redux/Images/Taskmaster_Screenshot2.jpg",
	'TagActivities', true,
	'TagGameplay', true,
})
