return PlaceObj('ModDef', {
	'title', "Jaggid's Taskmaster",
	'description', 'Added new work assignments for the Schedule planner so that work could be better scheduled and broke out several tasks into independent Activity groups for prioritization on the Acvitivy planner.\n\n[hr][/hr]\n[h1][b]Activity Planner[/b][/h1]\n[list][*]Split out Healing and Healing of Self so that you can prioritize them differently. \n[*]Split out the Handle task so that Rescue, Dismantle, Load and Manipulation can be seperately prioritized.  Note that "manipulation" covers the handling of devices, such as smelters, fermenters, making tea, etc. and "Load" is the loading and unloading of Trading Pods (as well as looting of corpses and burying the dead).\n[*]Split out the Hunting task so that Hunting, Butchering, and Slaughtering can each be prioritized seperately.  \n[*]Split out the Scavenging task so that Scavenge and Salvage can be prioritized seperately.\n[*]Split out the Construction activity so that Construction, Repairs, and Deconstruction can be prioritized seperately.\n[/list]\n\n[hr][/hr]\n[h1][b]Schedule Assignments[/b][/h1]\n[list][*][b]Farm[/b] (& Cook) - Cooking meals, as well as all farming/ranching related activities (including Cutting and Chopping) with no breaks to eat, relax or sleep.\n[*][b]Craft[/b] - All crafting tasks (including Tailoring and Soldering, etc., with no breaks for meals.\n[*][b]Work[/b] - Edited the game\'s default work assignment to remove \'eating\'.  For those times when you want your survivors NOT to stop for meal breaks.\n[*][b]Scavenge[/b] - Mining, scavenging and Salvaging.  No cutting or chopping.  With no breaks for meals.\n[*][b]Science[/b] - Research and Observation, with no breaks for meals.\n[*][b]Build[/b] - Construction related activities, including upgrades, repairs and deconstruction, with no Breaks for meals.\n[*][b]Sleep[/b] - Modified version of the game\'s standard Sleep assignment.  Forbids eating, so your survivors will not eat even if hungry until they wake up.  \n[/list]\nBe advised that all of the above new work schedule assignments have eating excluded.  So make sure to leave some time with other assignments in the schedule or your survivors might die. \n\nThe game\'s default work schedule groups of Anything and Relax also remain and do allow eating.\n\nDo not use with other mods that also adjust activity sets to avoid conflicts.',
	'image', "Mod/p7dPA7F/Images/Taskmaster_Preview.png",
	'last_changes', '1.10 - Removed "Work Hard" and replaced with an override of the game\'s "work" assignment which disables the option for survivors to eat when scheduled to work.  Changed color (and tooltip) as well to make it clear it is different.\n         - Removed "eating" from allowed activities when sleep is scheduled, per user request.  \n\nIf any users don\'t like either of these changes, please share that info with me in mod comments.  I assumed most people using the mod would be okay with the change, but I\'d like to know if I am mistaken.',
	'id', "p7dPA7F",
	'author', "Jaggid Edje",
	'version_major', 1,
	'version_minor', 10,
	'version', 168,
	'lua_revision', 233360,
	'saved_with_revision', 344982,
	'has_data', true,
	'saved', 1700318574,
	'screenshot1', "Mod/p7dPA7F/Images/Taskmaster_Screenshot1.jpg",
	'screenshot2', "Mod/p7dPA7F/Images/Taskmaster_Screenshot2.jpg",
	'steam_id', "2972040553",
	'TagActivities', true,
	'TagGameplay', true,
})